apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: universal-runtime
spec:
  selector:
    app: gateway
  ports:
    - {name: http, port: 8080, targetPort: http}
    - {name: control-grpc, port: 9092, targetPort: control-grpc}
