from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any


class ErrorCode(StrEnum):
    ADAPTER_NOT_SUPPORTED = "ADAPTER_NOT_SUPPORTED"
    CAPABILITY_NOT_SUPPORTED = "CAPABILITY_NOT_SUPPORTED"
    THREAD_BUSY = "THREAD_BUSY"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    INVALID_EXECUTION_INPUT = "INVALID_EXECUTION_INPUT"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
    EXECUTION_TIMEOUT = "EXECUTION_TIMEOUT"
    INFRASTRUCTURE_UNAVAILABLE = "INFRASTRUCTURE_UNAVAILABLE"
    FRAMEWORK_EXECUTION_FAILED = "FRAMEWORK_EXECUTION_FAILED"
    MIGRATION_LOCKED = "MIGRATION_LOCKED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    QUEUE_CLOSED = "QUEUE_CLOSED"
    STREAM_NOT_FOUND = "STREAM_NOT_FOUND"
    STREAM_CURSOR_INVALID = "STREAM_CURSOR_INVALID"
    STREAM_CURSOR_EXPIRED = "STREAM_CURSOR_EXPIRED"
    STREAM_BACKPRESSURE = "STREAM_BACKPRESSURE"
    EVENT_SEQUENCE_CONFLICT = "EVENT_SEQUENCE_CONFLICT"
    EVENT_SERIALIZATION_FAILED = "EVENT_SERIALIZATION_FAILED"
    PROJECTION_FAILED = "PROJECTION_FAILED"
    ARTIFACT_TOO_LARGE = "ARTIFACT_TOO_LARGE"
    ARTIFACT_STORE_FAILED = "ARTIFACT_STORE_FAILED"
    CUSTOM_HTTP_UNAVAILABLE = "CUSTOM_HTTP_UNAVAILABLE"
    CUSTOM_HTTP_TIMEOUT = "CUSTOM_HTTP_TIMEOUT"
    CUSTOM_HTTP_ENTRYPOINT_INVALID = "CUSTOM_HTTP_ENTRYPOINT_INVALID"
    CUSTOM_HTTP_DISCOVERY_AMBIGUOUS = "CUSTOM_HTTP_DISCOVERY_AMBIGUOUS"
    CUSTOM_HTTP_STARTUP_FAILED = "CUSTOM_HTTP_STARTUP_FAILED"
    CUSTOM_HTTP_RESPONSE_TOO_LARGE = "CUSTOM_HTTP_RESPONSE_TOO_LARGE"
    ASGI_ADAPTER_NOT_INSTALLED = "ASGI_ADAPTER_NOT_INSTALLED"
    ASGI_SYNTAX_ERROR = "ASGI_SYNTAX_ERROR"
    APPLICATION_MIGRATION_FAILED = "APPLICATION_MIGRATION_FAILED"


@dataclass(slots=True)
class RuntimeFailureError(Exception):
    code: ErrorCode
    message: str
    retryable: bool = False
    details: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        Exception.__init__(self, self.message)

    def __str__(self) -> str:
        return f"{self.code}: {self.message}"


RuntimeFailure = RuntimeFailureError
