from __future__ import annotations

from typing import Protocol

from universal_runtime.domain.assistants import Assistant
from universal_runtime.domain.execution import ExecutionRequest, Run, Thread


class AssistantRepository(Protocol):
    async def create(self, assistant: Assistant) -> Assistant: ...
    async def get(self, assistant_id: str) -> Assistant: ...


class ThreadRepository(Protocol):
    async def create(self, thread: Thread) -> Thread: ...
    async def get(self, thread_id: str) -> Thread: ...
    async def update(self, thread: Thread) -> Thread: ...


class RunRepository(Protocol):
    async def create(self, run: Run) -> Run: ...
    async def get(self, run_id: str) -> Run: ...
    async def update(self, run: Run) -> Run: ...
    async def active_for_thread(self, thread_id: str) -> Run | None: ...


class RequestValidator(Protocol):
    def validate(self, request: ExecutionRequest) -> None: ...
