from enum import StrEnum


class RuntimeEventType(StrEnum):
    RUN_QUEUED = "run.queued"
    RUN_STARTED = "run.started"
    RUN_COMPLETED = "run.completed"
    RUN_CANCELLED = "run.cancelled"
    RUN_FAILED = "run.failed"
    RUN_TIMEOUT = "run.timeout"
    RUN_INTERRUPTED = "run.interrupted"
    ATTEMPT_STARTED = "attempt.started"
    ATTEMPT_HEARTBEAT = "attempt.heartbeat"
    ATTEMPT_COMPLETED = "attempt.completed"
    ATTEMPT_FAILED = "attempt.failed"
    MESSAGE_STARTED = "message.started"
    MESSAGE_DELTA = "message.delta"
    MESSAGE_COMPLETED = "message.completed"
    AGENT_STARTED = "agent.started"
    AGENT_COMPLETED = "agent.completed"
    AGENT_FAILED = "agent.failed"
    TOOL_STARTED = "tool.started"
    TOOL_PROGRESS = "tool.progress"
    TOOL_COMPLETED = "tool.completed"
    TOOL_FAILED = "tool.failed"
    CUSTOM = "custom"
    STATE_VALUES = "state.values"
    STATE_UPDATES = "state.updates"
    CHECKPOINT_CREATED = "checkpoint.created"
    TASK_STARTED = "task.started"
    TASK_COMPLETED = "task.completed"
    INTERRUPT_CREATED = "interrupt.created"
    INTERRUPT_RESOLVED = "interrupt.resolved"
